### ISSUE TITLE
Restrict version to Julia 0.4 prerelease?

### ISSUE THREAD

**Issue by IainNZ** [bearnado/Pcap.jl#1]
It seems like this packages doesn't work on 0.3. It should really have a `REQUIRES` file that says that, i.e.

```
julia 0.4-
```

and the METADATA entry for the first tagged version should have a `requires` added to indicate it doesn't work.

**Comment by ghost** [comment]
lainNZ I knew that and I neglected to do so.  I do apologize and I just opened a pull request: https://github.com/JuliaLang/METADATA.jl/pull/2425

I will also make it a point as Julia Lang moves closer to 1.0 to support the stable versions as well.  I have just found with my other packages that I'm often times having to update depreciated logic or custom functions that are now part of the standard library with as fast as Julia's dev cycle is (which is awesome!).

Please let me know if this approach is not acceptable and I will develop to the stable versions vs the pre-release in the near-term for all my packages.  Thank you for bringing this to my attention.

**Comment by IainNZ** [comment]
Cool merged. I mean, whatever approach you take is up to you - personally, I stick to 0.3 and ignore 0.4 issues entirely, but I know some people have the other perspective. I'm just mainly interesting in ensuring that people get a working package if they are allowed to install it (I spotted Pcap was broken when I updated pkg.julialang.org). Thanks for doing that PR!

**Comment by ghost** [comment]
Before I get yelled at again, I sent another one your way:
https://github.com/JuliaLang/METADATA.jl/pull/2426 ;)
