### ISSUE TITLE
Pcap file endianness not handled

### ISSUE THREAD

**Issue by sergey-salnikov** [bearnado/Pcap.jl#2]
I recorded packets on a big-endian machine and tried reading them with Pcap.jl on a little-endian one:

```
julia> using Pcap

julia> cap = PcapOffline("big-endian-icmp-echo-request.pcap")
Pcap.PcapOffline("big-endian-icmp-echo-request.pcap",IOStream(<file big-endian-icmp-echo-request.pcap>),Pcap.PcapFileHeader(0x00000000,0x0000,0x0000,0,0x00000000,0x00000000,0x00000000),Pcap.PcapRec(0x00000000,0x00000000,0x00000000,0x00000000,UInt8[]),false)

julia> rec = pcap_get_record(cap)
Pcap.PcapRec(0xb0589556,0x104d0d00,0x62000000,0x62000000,UInt8[0xf8,0x1a,0x67,0x49,0x9f,0x9c,0x28,0xd2,0x44,0x46  …  0x2e,0x2f,0x30,0x31,0x32,0x33,0x34,0x35,0x36,0x37])

julia> cap.filehdr.version_major
0x0200

julia> rec.incl_len
0x62000000
```

`pcap_get_header` and `pcap_get_record` probably should use the magic number. Note that tcpdump can write 0xa1b2c3d4 (same-endian), 0xd4c3b2a1 (other-endian), 0xa1b23c4d (same-endian, nanosecond timestamps) and 0x4d3cb2a1 (other-endian, nanosecond timestamps).

Attaching [an example big-endian capture](https://github.com/r2dbg/Pcap.jl/files/87898/big-endian-icmp-echo-request.zip).

**Comment by zznop** [comment]
Sorry for the extremely late response @sergey-salnikov.  I somehow looked over your issue. I've added support for big endian and am merging with master now - thank you so much for the capture and bringing this to my attention!

```
julia> cap = PcapOffline("big-endian-icmp-echo-request.pcap")
Pcap.PcapOffline("big-endian-icmp-echo-request.pcap",IOStream(<file big-endian-icmp-echo-request.pcap>),Pcap.PcapFileHeader(0xd4c3b2a1,0x0002,0x0004,0,0x00000000,0x00040000,0x00000001),Pcap.PcapRec(0x00000000,0x00000000,0x00000000,0x00000000,UInt8[]),true)

julia> pcap_get_record(cap)
Pcap.PcapRec(0x569558b0,0x000d4d10,0x00000062,0x00000062,UInt8[0xf8,0x1a,0x67,0x49,0x9f,0x9c,0x28,0xd2,0x44,0x46  …  0x2e,0x2f,0x30,0x31,0x32,0x33,0x34,0x35,0x36,0x37])
```

**Comment by zznop** [comment]
Pushed to master (reference commit 0f48b5d7c0cb8f8fa61c9d2c952347d00a8f1482) run the following in the REPL:

```
Pkg.checkout("Pcap.jl")
```

I'll update METADATA soon. I'm currently working on wrapping libpcap for live capture so I'll tag a new version once I have some useful live capture functionality. For now just run the master branch for big endian caps.

Closing the issue.
