### ISSUE TITLE
Julia 1.0.1 Compatibility

### ISSUE THREAD

**Issue by olcaysah** [bearnado/Pcap.jl#7]
Hello, will there be any update in Julia Pcap package? Currently this package is not available to install on Julia V1.0.1.

Thanks.

**Comment by zak21rs** [comment]
My current fork is compatible with 1.0.1 https://github.com/zak21rs/Pcap.jl

**Comment by osahi001** [comment]
Thank you. It worked. But, in the example, the "hex(n)" function is deprecated. Use "string(n, base=16)" instead.
https://discourse.julialang.org/t/base-conversion-hex-bin-octal/15969/2

**Comment by zak21rs** [comment]
Your welcome, yes you are correct. I haven't  updated the readme yet but you can the formula you posted as hex(n) = string(n, base = 16, pad = 2)

**Comment by randyzwitch** [comment]
@zak21rs Are you planning on merging your fork back to this library?

**Comment by zak21rs** [comment]
I would love to, I just haven't received any feedback from the library's owner on my initial attempts to merge.

**Comment by zznop** [comment]
I haven’t reviewed your changes because you haven’t submitted a PR :)

**Comment by ki-chi** [comment]
This repo is very old; however, I've just found the guy looking for the solution today. I hope this repo can help them😄
https://discourse.julialang.org/t/parsing-pcap-files/65875
